<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add label'); ?>"
           href="<?php echo $this->url('', ['controller' => 'label', 'action' => 'update']); ?>"><i
                    class="fas fa-folder-open"></i> <?php _e('Add label'); ?></a>
    </p>

    <h3><?php _e('List of labels'); ?></h3>
    <table class="table table-striped table-bordered table-sm">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Ticket'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $label) { ?>
            <?php
            if ($label['status'] == 1) {
                $badgeIdClass = 'badge-success';
            } else {
                $badgeIdClass = 'badge-warning';
            }
            ?>
            <tr>
                <td><span
                            class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($label['id']); ?></span>
                </td>
                <td><?php echo $this->escape($label['title']); ?></td>
                <td><?php echo $this->escape($label['ticket']); ?></td>
                <td>
                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', ['action' => 'update', 'id' => $label['id']]); ?>"><i
                                class="fas fa-edit"></i> <?php _e('Edit'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>
