<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="page-header">
        <div class="clearfix row">
            <div class="col-md-8">
                <h1><?php echo $this->escape($title); ?></h1>
            </div>
            <div class="col-md-4 text-right ticket-label">
                <div class="label <?php echo $this->escape($ticket['status_class']); ?>">
                    <?php echo $this->escape($ticket['status_view']); ?>
                </div>
            </div>
        </div>
    </div>
    <?php if (isset($ticket) && !empty($ticket)) { ?>
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <div class="pull-left">
                    <?php echo $ticket['user']['avatar']; ?>
                    <?php echo $this->escape($ticket['user']['name']); ?>
                </div>
                <div class="pull-right">
                    <?php echo $this->escape($ticket['time_create_view']); ?>
                </div>
            </div>
            <div class="panel-body">
                <?php echo $ticket['message']; ?>
            </div>
            <?php if (!empty($ticket['file_path']) && !empty($ticket['file_name']) && $config['file_active']) { ?>
                <div class="panel-footer">
                    <a target="_blank" href="<?php echo $this->escape($ticket['file_url_admin']); ?>" title="<?php echo $this->escape($ticket['file_title_view']); ?>"><i class="fa fa-paperclip"></i> <?php echo $this->escape($ticket['file_title_view']); ?></a>
                </div>
            <?php } ?>
        </div>
    <?php } ?>
    <?php if (isset($tickets) && !empty($tickets)) { ?>
        <?php foreach ($tickets as $ticket) { ?>
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <div class="pull-left">
                        <?php echo $ticket['user']['avatar']; ?>
                        <?php echo $this->escape($ticket['user']['name']); ?>
                    </div>
                    <div class="pull-right">
                        <?php echo $this->escape($ticket['time_create_view']); ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo $ticket['message']; ?>
                </div>
                <?php if (!empty($ticket['file_path']) && !empty($ticket['file_name']) && $config['file_active']) { ?>
                    <div class="panel-footer">
                        <a target="_blank" href="<?php echo $this->escape($ticket['file_url_admin']); ?>" title="<?php echo $this->escape($ticket['file_title_view']); ?>"><i class="fa fa-paperclip"></i> <?php echo $this->escape($ticket['file_title_view']); ?></a>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
    <?php } ?>
    <div class="well">
        <?php echo $this->form($form, 'vertical'); ?>
    </div>
</div>