<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <?php if (isset($ticket) && !empty($ticket)) { ?>
        <div class="panel panel-default">
            <div class="panel-heading clearfix">
                <div class="pull-left">
                    <?php echo $ticket['user']['avatar']; ?>
                    <?php echo $this->escape($ticket['user']['name']); ?>
                </div>
                <div class="pull-right">
                    <?php echo $this->escape($ticket['time_create_view']); ?>
                </div>
            </div>
            <div class="panel-body">
                <?php echo $ticket['message']; ?>
            </div>
        </div>
    <?php } ?>
    <?php if (isset($tickets) && !empty($tickets)) { ?>
        <?php foreach ($tickets as $ticket) { ?>
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <div class="pull-left">
                        <?php echo $ticket['user']['avatar']; ?>
                        <?php echo $this->escape($ticket['user']['name']); ?>
                    </div>
                    <div class="pull-right">
                        <?php echo $this->escape($ticket['time_create_view']); ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo $ticket['message']; ?>
                </div>
            </div>
        <?php } ?>
    <?php } ?>
    <div class="well">
        <?php echo $this->form($form, 'vertical'); ?>
    </div>
</div>