<?php
$this->css($this->assetModule('css/admin.css'));
$this->backbone();
?>
<div id="js-ticket" class="clearfix">
    <div class="well well-sm">
        <ul class="nav nav-pills">
            <li<?php if ($status == 'open') { echo ' class="active"';} ?>>
                <a title="<?php _e('Opened tickets'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'ticket', 'action' => 'index', 'status' => 'open')); ?>"><?php _e('Opened tickets'); ?></a>
            </li>
            <li<?php if ($status == 'finish') { echo ' class="active"';} ?>>
                <a title="<?php _e('Finished tickets'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'ticket', 'action' => 'index', 'status' => 'finish')); ?>"><?php _e('Finished tickets'); ?></a>
            </li>
            <li<?php if ($status == 'all') { echo ' class="active"';} ?>>
                <a title="<?php _e('All tickets'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'ticket', 'action' => 'index', 'status' => 'all')); ?>"><?php _e('All tickets'); ?></a>
            </li>
            <li class="pull-right active">
                <a title="<?php _e('Open new support ticket'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'ticket', 'action' => 'update')); ?>">
                    <i class="fa fa-folder-open"></i> <?php _e('Open new support ticket'); ?>
                </a>
            </li>
        </ul>
    </div>
    <?php if (!empty($tickets)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('User'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th class="text-center"><?php _e('Status'); ?></th>
                <th class="text-center"><?php _e('Time'); ?></th>
            </tr>
            <?php foreach ($tickets as $ticket) { ?>
                <tr
                    data-id="<?php echo $this->escape($ticket['id']); ?>"
                    data-status="<?php echo Pi::url($this->url('', array('action' => 'updateStatus', 'id' => $ticket['id']))); ?>"
                >
                    <td class="text-center"><?php echo $this->escape($ticket['id']); ?></td>
                    <td>
                        <a data-toggle="modal" data-target="#userModal<?php echo $this->escape($ticket['id']); ?>">
                            <?php echo $this->escape($ticket['user']['name']); ?>
                        </a>
                        <div class="modal fade" id="userModal<?php echo $this->escape($ticket['id']); ?>" tabindex="-1" role="dialog" aria-labelledby="userModalLabel<?php echo $this->escape($ticket['id']); ?>">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <h4 class="modal-title" id="userModalLabel<?php echo $this->escape($ticket['id']); ?>">
                                            <?php echo sprintf(__('%s information'), $ticket['user']['name']); ?>
                                        </h4>
                                    </div>
                                    <div class="modal-body">
                                        <p><strong><?php _e('ID'); ?></strong> : <?php echo $this->escape($ticket['user']['id']); ?></p>
                                        <p><strong><?php _e('Identity'); ?></strong> : <?php echo $this->escape($ticket['user']['identity']); ?></p>
                                        <p><strong><?php _e('Name'); ?></strong> : <?php echo $this->escape($ticket['user']['name']); ?></p>
                                        <p><strong><?php _e('Email'); ?></strong> : <?php echo $this->escape($ticket['user']['email']); ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td>
                        <a href="<?php echo $this->escape($ticket['ticketUrl']); ?>">
                            <?php echo $this->escape($ticket['subject']); ?>
                        </a>
                    </td>
                    <td class="text-center">
                        <button id="update-status-<?php echo $this->escape($ticket['id']); ?>" class="update-status btn <?php echo $this->escape($ticket['status_btn']); ?> btn-xs">
                            <?php echo $this->escape($ticket['status_view']); ?>
                        </button>
                    </td>
                    <td class="text-center"><?php echo $this->escape($ticket['time_update_view']); ?></td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You didnt send any support ticket yet') ?>
        </div>
    <?php } ?>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-ticket'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.update-status').click(this.statusAction);
            },
            statusAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-status')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-status-' + p.attr('data-id')).attr('class', 'update-status btn ' + d.status_btn).html(d.status_view);
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>