<?php
$this->css($this->assetModule('css/admin.css'));
$this->backbone();
?>
<div id="js-ticket" class="clearfix">
    <div class="well well-sm clearfix">
        <div class="col-md-8">
            <?php echo $this->form($form, 'inline'); ?>
        </div>
        <ul class="nav nav-pills col-md-4">
            <li class="pull-right active">
                <a title="<?php _e('Open new support ticket'); ?>"
                   href="<?php echo $this->url('', array('controller' => 'ticket', 'action' => 'update')); ?>">
                    <i class="fas fa-folder-open"></i> <?php _e('Open new support ticket'); ?>
                </a>
            </li>
        </ul>
    </div>
    <?php if (!empty($tickets)) { ?>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th class="text-center small"><?php _e('ID'); ?></th>
                <th class="text-center small"><?php _e('User'); ?></th>
                <th class="small"><?php _e('Title'); ?></th>
                <th class="text-center small"><?php _e('Status / Label / Financial'); ?></th>
                <th class="text-center small"><?php _e('Time update'); ?></th>
                <th class="text-center small"><?php _e('Suggested time'); ?></th>
                <th class="text-center small"><?php _e('Execution time'); ?></th>
            </tr>
            <?php foreach ($tickets as $ticket) { ?>
                <tr
                    data-id="<?php echo $this->escape($ticket['id']); ?>"
                    data-status="<?php echo Pi::url($this->url('', array('action' => 'updateStatus', 'id' => $ticket['id']))); ?>"
                >
                    <td class="text-center small"><?php echo $this->escape($ticket['id']); ?></td>
                    <td>
                        <a class="text-center small" data-toggle="modal" data-target="#userModal<?php echo $this->escape($ticket['id']); ?>">
                            <?php echo $this->escape($ticket['user']['name']); ?>
                        </a>
                        <div class="modal fade" id="userModal<?php echo $this->escape($ticket['id']); ?>" tabindex="-1" role="dialog" aria-labelledby="userModalLabel<?php echo $this->escape($ticket['id']); ?>">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="userModalLabel<?php echo $this->escape($ticket['id']); ?>">
                                            <?php echo sprintf(__('%s information'), $ticket['user']['name']); ?>
                                        </h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="<?php _e('Close'); ?>">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p><strong><?php _e('ID'); ?></strong> : <?php echo $this->escape($ticket['user']['id']); ?></p>
                                        <p><strong><?php _e('Identity'); ?></strong> : <?php echo $this->escape($ticket['user']['identity']); ?></p>
                                        <p><strong><?php _e('Name'); ?></strong> : <?php echo $this->escape($ticket['user']['name']); ?></p>
                                        <p><strong><?php _e('Email'); ?></strong> : <?php echo $this->escape($ticket['user']['email']); ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td class="small">
                        <a href="<?php echo $this->escape($ticket['ticketUrl']); ?>">
                            <?php echo $this->escape($ticket['subject']); ?>
                        </a>
                    </td>
                    <td class="text-center small">
                        <button id="update-status-<?php echo $this->escape($ticket['id']); ?>" class="update-status btn btn-sm <?php echo $this->escape($ticket['status_btn']); ?>">
                            <?php echo $this->escape($ticket['status_view']); ?>
                        </button>
                        <span id="update-label-<?php echo $this->escape($ticket['id']); ?>" class="label" style="background: <?php echo $this->escape($ticket['label_color']); ?>"><?php echo $this->escape($ticket['label_title']); ?></span>
                        <span id="update-status-financial-<?php echo $this->escape($ticket['id']); ?>" class="label <?php echo $this->escape($ticket['status_financial_class']); ?>"><?php echo $this->escape($ticket['status_financial_view']); ?></span>
                    </td>
                    <td class="text-center small"><?php echo $this->escape($ticket['time_update_view']); ?></td>
                    <td class="text-center small" id="update-time-suggested-<?php echo $this->escape($ticket['id']); ?>"><?php echo $this->escape($ticket['time_suggested_view']); ?></td>
                    <td class="text-center small" id="update-time-execution-<?php echo $this->escape($ticket['id']); ?>"><?php echo $this->escape($ticket['time_execution_view']); ?></td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You didnt send any support ticket yet') ?>
        </div>
    <?php } ?>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>
<script>
    (function ($) {
        var page = {
            el: $('#js-ticket'),
            modal: $('<div class="modal fade">').appendTo(document.body),
            $: function (selector) {
                return this.el.find(selector);
            },
            init: function () {
                _.bindAll(this);
                this.$('.update-status').click(this.statusAction);
            },
            statusAction: function (e) {
                var p = $(e.target).parents('tr'),
                    self = this;
                $.get(p.attr('data-status')).done(function (res) {
                    self.modal.html(res).modal('show');
                    formModule.success = function (res) {
                        var d = res.data;
                        self.modal.html(res).modal('hide');
                        $('#update-status-' + p.attr('data-id')).attr('class', 'update-status btn btn-sm ' + d.status_btn).html(d.status_view);
                        $('#update-status-financial-' + p.attr('data-id')).attr('class', 'label ' + d.status_financial_class).html(d.status_financial_view);
                        $('#update-label-' + p.attr('data-id')).attr('style',  'background: ' + d.label_color).html(d.label_title);
                        $('#update-time-suggested-' + p.attr('data-id')).html(d.time_suggested_view);
                        $('#update-time-execution-' + p.attr('data-id')).html(d.time_execution_view);
                    };
                });
            },
        }
        page.init();
    })(jQuery)
</script>