<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of your submitted tickets') ?></h3>
    <div class="clearfix">
        <div class="col-md-8">
            <ul class="list-inline">
                <li><?php echo $user['avatar']; ?></li>
                <li><?php echo $this->escape($user['name']); ?></li>
            </ul>
        </div>
        <div class="col-md-4 text-right">
            <a title="<?php _e('New ticket') ?>" class="btn btn-success" href="<?php echo $this->escape($submit); ?>">
                <i class="fa fa-plus"></i> <?php _e('New ticket') ?>
            </a>
        </div>
    </div>
    <hr />
    <div class="clearfix">
        <?php if (!empty($tickets)) { ?>
            <table class="table table-striped table-bordered table-condensed">
                <tr>
                    <th><?php _e('Title'); ?></th>
                    <th><?php _e('Status'); ?></th>
                    <th><?php _e('Action'); ?></th>
                </tr>
                <?php foreach ($tickets as $ticket) { ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->escape($ticket['ticketUrl']); ?>">
                                <?php echo $this->escape($ticket['subject']); ?>
                            </a>
                        </td>
                        <td><?php echo $this->escape($ticket['status_view']); ?></td>
                        <td><?php echo $this->escape($ticket['time_create_view']); ?></td>
                    </tr>
                <?php } ?>
            </table>
            <p>
                <span class="label label-success"><?php _e('Published'); ?></span>
                <span class="label label-warning"><?php _e('Pending review'); ?></span>
                <span class="label label-default"><?php _e('Edit by user'); ?></span>
                <span class="label label-info"><?php _e('Draft'); ?></span>
                <span class="label label-danger"><?php _e('Trash'); ?></span>
            </p>
        <?php } else { ?>
            <div class="alert alert-danger" role="alert">
                <?php _e('You didnt send any support ticket yet') ?>
            </div>
        <?php } ?>
    </div>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>

</div>