<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="row user-section-wrapper">
        <?php if ($config['show_userbar']) { ?>
            <div class="col-md-3">
                <?php $sideActive = 'support'; ?>
                <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
            </div>
        <?php } ?>
        <div class="<?php if ($config['show_userbar']) { ?>col-md-9<?php } else { ?>col-md-12<?php } ?>">

            <div class="clearfix">
                <div class="clearfix row mb-3">
                    <div class="col-md-6">
                        <h1><?php _e('Tickets') ?></h1>
                    </div>
                    <div class="col-md-6 text-right">
                        <a title="<?php _e('New ticket') ?>" class="btn btn-success" href="<?php echo $this->escape($submit); ?>">
                            <i class="fas fa-plus"></i> <?php _e('New ticket') ?>
                        </a>
                    </div>
                </div>

                <?php if (!empty($tickets)) { ?>
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
                        <tr>
                            <th class="text-center"><?php _e('Ticket ID'); ?></th>
                            <th class="text-center"><?php _e('Title'); ?></th>
                            <?php if (isset($config['has_department']) && !empty($config['has_department'])) { ?>
                                <th class="text-center"><?php _e('Department'); ?></th>
                            <?php } ?>
                            <th class="text-center"><?php _e('Status'); ?></th>
                            <th class="text-center"><?php _e('Time update'); ?></th>
                            <th class="text-center"><?php _e('Action'); ?></th>
                        </tr>
                        <?php foreach ($tickets as $ticket) { ?>
                            <tr>
                                <td class="text-center"><?php echo $this->escape($ticket['id']); ?></td>
                                <td class="text-center">
                                    <a href="<?php echo $this->escape($ticket['ticketUrl']); ?>">
                                        <?php echo $this->escape($ticket['subject']); ?>
                                    </a>
                                </td>
                                <?php if (isset($config['has_department']) && !empty($config['has_department'])) { ?>
                                    <td class="text-center"><?php echo $this->escape($ticket['label_title']); ?></td>
                                <?php } ?>
                                <td class="text-center">
                                    <div class="badge <?php echo $this->escape($ticket['status_class']); ?>">
                                        <?php echo $this->escape($ticket['status_view']); ?>
                                    </div>
                                </td>
                                <td class="text-center"><?php echo $this->escape($ticket['time_update_view']); ?></td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-sm" href="<?php echo $this->escape($ticket['ticketUrl']); ?>">
                                        <?php _e('View'); ?>
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    </table>
                </div>
                <?php } else { ?>
                    <div class="alert alert-danger" role="alert">
                        <?php _e('You do not have any support tickets') ?>
                    </div>
                <?php } ?>
            </div>
            <div class="paginator">
                <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
            </div>
        </div>
    </div>
</div>
