<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="page-header">
        <div class="clearfix">
            <div class="col-md-8">
                <h1><?php _e('List of your submitted tickets') ?></h1>
            </div>
            <div class="col-md-4 text-right">
                <a title="<?php _e('New ticket') ?>" class="btn btn-success" href="<?php echo $this->escape($submit); ?>">
                    <i class="fa fa-plus"></i> <?php _e('New ticket') ?>
                </a>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <div class="clearfix">
            <?php if (!empty($tickets)) { ?>
                <table class="table table-striped table-bordered table-condensed">
                    <tr>
                        <th class="col-md-7"><?php _e('Title'); ?></th>
                        <th class="col-md-2 text-center"><?php _e('Status'); ?></th>
                        <th class="col-md-3 text-center"><?php _e('Time'); ?></th>
                    </tr>
                    <?php foreach ($tickets as $ticket) { ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->escape($ticket['ticketUrl']); ?>">
                                    <?php echo $this->escape($ticket['subject']); ?>
                                </a>
                            </td>
                            <td class="text-center">
                            <span class="label <?php echo $this->escape($ticket['status_class']); ?>">
                                <?php echo $this->escape($ticket['status_view']); ?>
                            </span>
                            </td>
                            <td class="text-center"><?php echo $this->escape($ticket['time_update_view']); ?></td>
                        </tr>
                    <?php } ?>
                </table>
            <?php } else { ?>
                <div class="alert alert-danger" role="alert">
                    <?php _e('You didnt send any support ticket yet') ?>
                </div>
            <?php } ?>
        </div>
        <div class="paginator">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
        </div>
    </div>
</div>