<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <?php $sideActive = 'support'; ?>
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
        <div class="col-md-9">
            <?php if (isset($ticketMain) && !empty($ticketMain)) { ?>
                <div class="clearfix">
                    <div class="alert alert-info" role="alert">
                        <ul class="list-inline clearfix">
                            <li>
                                <?php _e('Status'); ?> : <span class="label <?php echo $this->escape($ticketMain['status_class']); ?>">
                            <?php echo $this->escape($ticketMain['status_view']); ?></span>
                            </li>
                            <li>
                                <?php _e('Suggested time'); ?> : <strong><?php echo $this->escape($ticketMain['time_suggested_view']); ?></strong>
                            </li>
                            <li>
                                <?php _e('Execution time'); ?> : <strong><?php echo $this->escape($ticketMain['time_execution_view']); ?></strong>
                            </li>
                            <li>
                                <?php _e('Last update'); ?> : <strong><?php echo $this->escape($ticketMain['time_update_view']); ?></strong>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <div class="pull-left">
                            <?php echo $ticketMain['user']['avatar']; ?>
                            <?php echo $this->escape($ticketMain['user']['name']); ?>
                        </div>
                        <div class="pull-right">
                            <?php echo $this->escape($ticketMain['time_create_view']); ?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <?php echo $ticketMain['message']; ?>
                        <?php if (!empty($ticketMain['file_path']) && !empty($ticketMain['file_name'])&& $config['file_active']) { ?>
                            <div class="panel-footer">
                                <a target="_blank" href="<?php echo $this->escape($ticketMain['file_url_user']); ?>" title="<?php echo $this->escape($ticketMain['file_title_view']); ?>"><i class="fa fa-paperclip"></i> <?php echo $this->escape($ticketMain['file_title_view']); ?></a>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
            <?php if (isset($tickets) && !empty($tickets)) { ?>
                <?php foreach ($tickets as $ticket) { ?>
                    <div class="panel panel-default">
                        <div class="panel-heading clearfix">
                            <div class="pull-left">
                                <?php echo $ticket['user']['avatar']; ?>
                                <?php echo $this->escape($ticket['user']['name']); ?>
                            </div>
                            <div class="pull-right">
                                <?php echo $this->escape($ticket['time_create_view']); ?>
                            </div>
                        </div>
                        <div class="panel-body">
                            <?php echo $ticket['message']; ?>
                        </div>
                        <?php if (!empty($ticket['file_path']) && !empty($ticket['file_name']) && $config['file_active']) { ?>
                            <div class="panel-footer">
                                <a target="_blank" href="<?php echo $this->escape($ticket['file_url_user']); ?>" title="<?php echo $this->escape($ticket['file_title_view']); ?>"><i class="fa fa-paperclip"></i> <?php echo $this->escape($ticket['file_title_view']); ?></a>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            <?php } ?>
            <?php if (isset($ticketMain['status']) && $ticketMain['status'] == 5) { ?>
                <div class="well">
                    <?php _e('This ticket finished, for more suppoert please open new ticket'); ?>
                </div>
            <?php } elseif (isset($ticketMain['status']) && $ticketMain['status'] == 6) { ?>
                <div class="well">
                    <?php _e('This ticket holded, please wait our support team finish your other support requests, after that we will work on this ticket'); ?>
                </div>
            <?php } else { ?>
                <div class="well">
                    <?php echo $this->form($form, 'vertical'); ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>