<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <div class="page-header">
        <h1><?php echo $this->escape($title); ?></h1>
    </div>
    <div class="col-md-3">
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <?php if (isset($ticket) && !empty($ticket)) { ?>
            <div class="clearfix">
                <?php _e('Status'); ?> : <span class="label <?php echo $this->escape($ticket['status_class']); ?>"><?php echo $this->escape($ticket['status_view']); ?></span>
            </div>
            <br />
            <div class="panel panel-default">
                <div class="panel-heading clearfix">
                    <div class="pull-left">
                        <?php echo $ticket['user']['avatar']; ?>
                        <?php echo $this->escape($ticket['user']['name']); ?>
                    </div>
                    <div class="pull-right">
                        <?php echo $this->escape($ticket['time_create_view']); ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?php echo $ticket['message']; ?>
                </div>
            </div>
        <?php } ?>
        <?php if (isset($tickets) && !empty($tickets)) { ?>
            <?php foreach ($tickets as $ticket) { ?>
                <div class="panel panel-default">
                    <div class="panel-heading clearfix">
                        <div class="pull-left">
                            <?php echo $ticket['user']['avatar']; ?>
                            <?php echo $this->escape($ticket['user']['name']); ?>
                        </div>
                        <div class="pull-right">
                            <?php echo $this->escape($ticket['time_create_view']); ?>
                        </div>
                    </div>
                    <div class="panel-body">
                        <?php echo $ticket['message']; ?>
                    </div>
                </div>
            <?php } ?>
        <?php } ?>
        <?php if (!isset($ticket) || in_array($ticket['status'], array(1,2,3,4))) { ?>
        <div class="well">
            <?php echo $this->form($form, 'vertical'); ?>
        </div>
        <?php } elseif ($ticket['status'] == 5) { ?>
            <div class="well">
                <?php _e('This ticket finished, for more suppoert please open new ticket'); ?>
            </div>
        <?php } ?>
    </div>
</div>